graph TD
    subgraph Web [Capa Web - MVC]
        C[Controllers]
        V[Views]
    end

    subgraph Application [Capa Application - Lógica]
        S[Services]
        I[Interfaces IRepository]
    end

    subgraph Infrastructure [Capa Infrastructure]
        R[JsonRepositories]
    end

    subgraph Domain [Capa Domain - Entidades]
        E[Entities: Book, Goal]
    end

    C --> S
    S --> I
    R -.-> I
    S --> E